/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package group.lab;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

       String imagepath = args[0];
       BufferedImage uplFile =  BitMap.bitMapImgUpload(imagepath);
//       uplFile = BitMap.changeColorImg(uplFile);
       ImageIO.write(uplFile,"BMP", new File(imagepath));
       System.out.println("filr saved");



    }
}
