/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package group.lab;

import java.awt.image.BufferedImage;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {

       if(args[1].equals("delete")){
           BitMap.DelImg(args[0]);
           return ;
       }

       if(args[2].equals("shrink")){
           BufferedImage file = BitMap.bitMapImgUpload(args[0]);
           BufferedImage filer = BitMap.CopImg(file);
           BitMap.saveImge(filer, args[1]);
            return ;
       }
       if(args[2].equals("bingo")){
           BufferedImage file = BitMap.bitMapImgUpload(args[0]);
           BufferedImage filer = BitMap.changeColorImg(file);
           BitMap.saveImge(filer,args[1]);
       }
    }
}
